# Generated by Django 2.1.1 on 2018-09-20 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign1', '0004_auto_20180920_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=30)),
                ('currentTime', models.DateTimeField(null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign1.UserData')),
            ],
        ),
    ]
